Repository OCA/operating-unit, pull requests merged in 2020-10, with the labels that each got.

#323 [FIX] This line leads the test to an error but the module is well installed
  purchase_operating_unit/README.rst
  purchase_operating_unit/readme/CONTRIBUTORS.rst
  purchase_operating_unit/tests/test_purchase_operating_unit.py
Labels: bot is merging ⏳

#322 [IMP] sales_team_operating_unit v12: Adding default operating unit for existing demo Sales Team
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/demo/sales_team_demo.xml
Labels: approved, bot is merging ⏳

#325 [13.0][MIG] hr_contract_operating_unit
  hr_contract_operating_unit/README.rst
  hr_contract_operating_unit/__init__.py
  hr_contract_operating_unit/__manifest__.py
  hr_contract_operating_unit/i18n/hr_contract_operating_unit.pot
  hr_contract_operating_unit/i18n/pt.po
  hr_contract_operating_unit/models/__init__.py
  hr_contract_operating_unit/models/hr_contract.py
  hr_contract_operating_unit/readme/CONTRIBUTORS.rst
  hr_contract_operating_unit/readme/DESCRIPTION.rst
  hr_contract_operating_unit/readme/USAGE.rst
  hr_contract_operating_unit/security/hr_contract_security.xml
  hr_contract_operating_unit/static/description/icon.png
  hr_contract_operating_unit/static/description/index.html
  hr_contract_operating_unit/tests/__init__.py
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  hr_contract_operating_unit/views/hr_contract_view.xml
Labels: approved, bot is merging ⏳

#312 [13.0]fix operating_unit record rules
  operating_unit/models/res_users.py
  operating_unit/security/operating_unit_security.xml
  operating_unit/tests/test_operating_unit.py
Labels: approved, bot is merging ⏳, ready to merge

#328 [14.0][MIG] migration of module operating_unit
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/readme/CONFIGURE.rst
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/readme/DESCRIPTION.rst
  operating_unit/readme/ROADMAP.rst
  operating_unit/readme/USAGE.rst
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
  setup/operating_unit/odoo/addons/operating_unit
  setup/operating_unit/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#334 [12.0] [FIX] The Default Operating Unit of the user is not assigned to it.
  product_operating_unit/models/product_template.py
Labels: approved, bot is merging ⏳

#329 [14.0][MIG] migration of module sales_team_operating_unit
  sales_team_operating_unit/README.rst
  sales_team_operating_unit/__init__.py
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/i18n/es_MX.po
  sales_team_operating_unit/i18n/sales_team_operating_unit.pot
  sales_team_operating_unit/models/__init__.py
  sales_team_operating_unit/models/crm_team.py
  sales_team_operating_unit/readme/CONTRIBUTORS.rst
  sales_team_operating_unit/readme/DESCRIPTION.rst
  sales_team_operating_unit/readme/USAGE.rst
  sales_team_operating_unit/security/crm_security.xml
  sales_team_operating_unit/static/description/icon.png
  sales_team_operating_unit/static/description/index.html
  sales_team_operating_unit/tests/__init__.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  sales_team_operating_unit/views/crm_team_view.xml
  setup/sales_team_operating_unit/odoo/addons/sales_team_operating_unit
  setup/sales_team_operating_unit/setup.py
Labels: approved, bot is merging ⏳, ready to merge
