Repository OCA/operating-unit, pull requests merged in 2020-03, with the labels that each got.

#260 [IMP] stock_operating_unit: Group By Error + Location OnChange
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/model/__init__.py
  stock_operating_unit/models/__init__.py
  stock_operating_unit/models/product_product.py
  stock_operating_unit/models/stock_location.py
  stock_operating_unit/models/stock_move.py
  stock_operating_unit/models/stock_picking.py
  stock_operating_unit/models/stock_rule.py
  stock_operating_unit/models/stock_warehouse.py
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/view/stock.xml
  stock_operating_unit/view/stock_picking.xml
Labels: approved, enhancement, needs review, ready to merge

#261 [IMP] project_operating_unit: Group By Operating Unit Projects
  project_operating_unit/views/project_project.xml
Labels: approved, enhancement, needs review, ready to merge

#264 [FIX] stock_operating_unit: Set Picking OU as Location OU
  stock_operating_unit/models/stock_picking.py
Labels: approved, bug

#262 [FIX] res_partner_operating_unit: Perf issue (#258)
  res_partner_operating_unit/__manifest__.py
  res_partner_operating_unit/models/res_partner.py
  res_partner_operating_unit/security/res_partner_security.xml
Labels: approved, bug, needs review, ready to merge

#266 [IMP] res_partner_operating_unit (Add Widget on List)
  res_partner_operating_unit/views/res_partner_view.xml
Labels: approved, enhancement, needs review

#267 [IMP] stock_operating_unit (Update Record Rule)
  stock_operating_unit/security/stock_security.xml
Labels: approved, enhancement, needs review

#265 [FIX] stock_operating_unit: Constraint on stock move
  stock_operating_unit/models/stock_move.py
Labels: approved, bug, needs review, ready to merge
