Repository OCA/operating-unit, pull requests merged in 2020-07, with the labels that each got.

#303 [12.0][FIX] agreement_operating_unit
  agreement_operating_unit/__manifest__.py
  agreement_operating_unit/tests/test_agreement_operating_unit.py
Labels: approved, bot is merging ⏳, bug

#304 [12.0][FIX] purchase_operating_unit
  purchase_operating_unit/tests/test_purchase_operating_unit.py
Labels: approved, bot is merging ⏳, bug, needs review

#222 [12.0][ADD] sale_multi_operating_unit
  oca_dependencies.txt
  sale_multi_operating_unit/README.rst
  sale_multi_operating_unit/__init__.py
  sale_multi_operating_unit/__manifest__.py
  sale_multi_operating_unit/models/__init__.py
  sale_multi_operating_unit/models/crm_lead.py
  sale_multi_operating_unit/models/res_company.py
  sale_multi_operating_unit/models/sale_order.py
  sale_multi_operating_unit/models/sale_order_quote.py
  sale_multi_operating_unit/models/sale_order_quote_line.py
  sale_multi_operating_unit/readme/CONTRIBUTORS.rst
  sale_multi_operating_unit/readme/CREDITS.rst
  sale_multi_operating_unit/readme/DESCRIPTION.rst
  sale_multi_operating_unit/readme/USAGE.rst
  sale_multi_operating_unit/security/ir.model.access.csv
  sale_multi_operating_unit/security/ir_rule.xml
  sale_multi_operating_unit/tests/__init__.py
  sale_multi_operating_unit/tests/test_sale_multi_operating_unit.py
  sale_multi_operating_unit/views/res_company.xml
  sale_multi_operating_unit/views/sale_order_view.xml
Labels: bot is merging ⏳, enhancement, needs review

#290 [12.0][FIX] stock_operating_unit depends on operating_unit
  stock_operating_unit/__manifest__.py
Labels: approved, bot is merging ⏳

#298 [IMP] stock_operating_unit: Check Destination Location OU is Set
  stock_operating_unit/models/stock_move.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge
