Repository OCA/operating-unit, pull requests merged in 2020-02, with the labels that each got.

#241 [IMP] Default Operating Unit Company Dependant
  operating_unit/models/res_users.py
Labels: approved, ready to merge

#246 13.0 operating unit column renamed
  .isort.cfg
  operating_unit/migrations/13.0.1.0.0/pre-migration.py
  operating_unit/readme/ROADMAP.rst
Labels: approved

#247 [12.0][REV]company dependent field in operating_unit
  operating_unit/models/res_users.py
Labels: approved

#240 [IMP] purchase_operating_unit: Enable Multi Picking/Warehouse on PO's
  purchase_operating_unit/models/purchase_order.py
Labels: approved, enhancement, needs review

#249 [12.0][FIX] account_operating_unit: Fix refund creation
  account_operating_unit/models/account_invoice.py
Labels: approved

#257 [13.0][FIX] operating_unit: multicompany rule
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/security/operating_unit_security.xml
Labels: approved
