Repository OCA/operating-unit, pull requests merged in 2021-08, with the labels that each got.

#392 [14.0][FIX] purchase_operating_unit, add OU when create invoice
  purchase_operating_unit/models/purchase_order.py
Labels: approved, bot is merging ⏳

#336 [12.0][FIX] res_partner_operating_unit: Fixed an issue of getting trace-back when logged In user going to change the Default Operating Unit.
  res_partner_operating_unit/models/res_users.py
Labels: approved, bot is merging ⏳, ready to merge

#404 [14.0][MIG] agreement_operating_unit
  agreement_operating_unit/README.rst
  agreement_operating_unit/__init__.py
  agreement_operating_unit/__manifest__.py
  agreement_operating_unit/i18n/agreement_operating_unit.pot
  agreement_operating_unit/i18n/pt.po
  agreement_operating_unit/models/__init__.py
  agreement_operating_unit/models/agreement.py
  agreement_operating_unit/models/agreement_serviceprofile.py
  agreement_operating_unit/readme/CONTRIBUTORS.rst
  agreement_operating_unit/readme/CREDITS.rst
  agreement_operating_unit/readme/DESCRIPTION.rst
  agreement_operating_unit/readme/USAGE.rst
  agreement_operating_unit/security/aggreement_security.xml
  agreement_operating_unit/static/description/icon.png
  agreement_operating_unit/static/description/index.html
  agreement_operating_unit/tests/__init__.py
  agreement_operating_unit/tests/test_agreement_operating_unit.py
  agreement_operating_unit/views/agreement.xml
  agreement_operating_unit/views/agreement_serviceprofile.xml
  setup/agreement_operating_unit/odoo/addons/agreement_operating_unit
  setup/agreement_operating_unit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#401 [14.0][MIG] product_operating_unit
  product_operating_unit/README.rst
  product_operating_unit/__init__.py
  product_operating_unit/__manifest__.py
  product_operating_unit/i18n/product_operating_unit.pot
  product_operating_unit/i18n/pt.po
  product_operating_unit/models/__init__.py
  product_operating_unit/models/product_category.py
  product_operating_unit/models/product_template.py
  product_operating_unit/readme/CONTRIBUTORS.rst
  product_operating_unit/readme/DESCRIPTION.rst
  product_operating_unit/readme/ROADMAP.rst
  product_operating_unit/readme/USAGE.rst
  product_operating_unit/security/product_template_security.xml
  product_operating_unit/static/description/icon.png
  product_operating_unit/static/description/index.html
  product_operating_unit/tests/__init__.py
  product_operating_unit/tests/test_product_operating_unit.py
  product_operating_unit/views/product_category_view.xml
  product_operating_unit/views/product_template_view.xml
  setup/product_operating_unit/odoo/addons/product_operating_unit
  setup/product_operating_unit/setup.py
Labels: needs review, migration, bot is merging ⏳

#400 [12.0][FIX] analytic_operating_unit: Error search OUs in analytic account
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/views/analytic_account_view.xml
Labels: approved, bot is merging ⏳

#412 [FIX] stock_operating_unit: fix warning in orderpoint constraint
  stock_operating_unit/model/stock_warehouse.py
Labels: bot is merging ⏳
