Repository OCA/operating-unit, pull requests merged in 2022-05, with the labels that each got.

#465 [14.0][ADD] mis_builder_operating_unit_access_all
  mis_builder_operating_unit_access_all/README.rst
  mis_builder_operating_unit_access_all/__init__.py
  mis_builder_operating_unit_access_all/__manifest__.py
  mis_builder_operating_unit_access_all/readme/CONFIGURE.rst
  mis_builder_operating_unit_access_all/readme/CONTRIBUTORS.rst
  mis_builder_operating_unit_access_all/readme/DESCRIPTION.rst
  mis_builder_operating_unit_access_all/security/mis_builder_security.xml
  mis_builder_operating_unit_access_all/static/description/icon.png
  mis_builder_operating_unit_access_all/static/description/index.html
  setup/mis_builder_operating_unit_access_all/odoo/addons/mis_builder_operating_unit_access_all
  setup/mis_builder_operating_unit_access_all/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#475 [14.0][MIG] report_qweb_operating_unit
  report_qweb_operating_unit/README.rst
  report_qweb_operating_unit/__init__.py
  report_qweb_operating_unit/__manifest__.py
  report_qweb_operating_unit/i18n/es_MX.po
  report_qweb_operating_unit/i18n/report_qweb_operating_unit.pot
  report_qweb_operating_unit/readme/CONTRIBUTORS.rst
  report_qweb_operating_unit/readme/DESCRIPTION.rst
  report_qweb_operating_unit/static/description/icon.png
  report_qweb_operating_unit/static/description/index.html
  report_qweb_operating_unit/views/report_qweb_operating_unit.xml
  setup/report_qweb_operating_unit/odoo/addons/report_qweb_operating_unit
  setup/report_qweb_operating_unit/setup.py
Labels: approved, bot is merging ⏳

#194 [12.0] [ADD] hr_operating_unit
  hr_operating_unit/README.rst
  hr_operating_unit/__init__.py
  hr_operating_unit/__manifest__.py
  hr_operating_unit/i18n/es.po
  hr_operating_unit/i18n/hr_operating_unit.pot
  hr_operating_unit/models/__init__.py
  hr_operating_unit/models/hr_employee.py
  hr_operating_unit/models/hr_operating_unit.py
  hr_operating_unit/readme/CONTRIBUTORS.rst
  hr_operating_unit/readme/DESCRIPTION.rst
  hr_operating_unit/readme/USAGE.rst
  hr_operating_unit/security/security.xml
  hr_operating_unit/static/description/index.html
  hr_operating_unit/views/hr_employee.xml
Labels: enhancement, question, needs review, bot is merging ⏳, stale
