Repository OCA/operating-unit, pull requests merged in 2022-04, with the labels that each got.

#436 [14.0][FIX] Access all OU on stock.move
  stock_operating_unit_access_all/security/stock_security.xml
Labels: approved, ready to merge, bot is merging ⏳

#471 [14.0][IMP] travis to github-actions
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  .test.yml
  README.md
  account_asset_operating_unit_access_all/__manifest__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  contract_operating_unit/README.rst
  contract_operating_unit/__init__.py
  contract_operating_unit/__manifest__.py
  contract_operating_unit/models/contract.py
  contract_operating_unit/static/description/index.html
  contract_operating_unit/tests/test_contract_operating_unit.py
  mis_builder_budget_operating_unit/README.rst
  mis_builder_budget_operating_unit/__manifest__.py
  mis_builder_budget_operating_unit/models/mis_budget_item.py
  mis_builder_budget_operating_unit/static/description/index.html
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/static/description/index.html
Labels: bot is merging ⏳

#451 [14.0][FIX] account_financial_report_operating_unit: rename function
  account_financial_report_operating_unit/report/aged_partner_balance.py
  account_financial_report_operating_unit/report/open_items.py
Labels: approved, bot is merging ⏳

#469 [14.0][FIX] purchase_requisition_operating_unit: delete duplicate field
  purchase_requisition_operating_unit/view/purchase_requisition.xml
Labels: approved, bot is merging ⏳
