Repository OCA/operating-unit, pull requests merged in 2022-10, with the labels that each got.

#391 [14.0][ADD] account_operating_unit_access_all
  account_operating_unit_access_all/__init__.py
  account_operating_unit_access_all/__manifest__.py
  account_operating_unit_access_all/readme/CONFIGURE.rst
  account_operating_unit_access_all/readme/CONTRIBUTORS.rst
  account_operating_unit_access_all/readme/DESCRIPTION.rst
  account_operating_unit_access_all/security/account_security.xml
  account_operating_unit_access_all/static/description/icon.png
  setup/account_operating_unit_access_all/odoo/addons/account_operating_unit_access_all
  setup/account_operating_unit_access_all/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#506 [IMP][14.0] operating unit: updated validation for allowed operating unit
  operating_unit/models/res_users.py
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/res_users_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#476 [14.0][ADD] contract_operating_unit_access_all
  contract_operating_unit_access_all/__init__.py
  contract_operating_unit_access_all/__manifest__.py
  contract_operating_unit_access_all/readme/CONFIGURE.rst
  contract_operating_unit_access_all/readme/CONTRIBUTORS.rst
  contract_operating_unit_access_all/readme/DESCRIPTION.rst
  contract_operating_unit_access_all/security/contract_security.xml
  contract_operating_unit_access_all/static/description/icon.png
  setup/contract_operating_unit_access_all/odoo/addons/contract_operating_unit_access_all
  setup/contract_operating_unit_access_all/setup.py
Labels: approved, bot is merging ⏳

#472 [14.0][MIG] hr_payroll_account_operating_unit
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  hr_payroll_account_operating_unit/README.rst
  hr_payroll_account_operating_unit/__init__.py
  hr_payroll_account_operating_unit/__manifest__.py
  hr_payroll_account_operating_unit/i18n/hr_payroll_account_operating_unit.pot
  hr_payroll_account_operating_unit/i18n/pt.po
  hr_payroll_account_operating_unit/models/__init__.py
  hr_payroll_account_operating_unit/models/account_move.py
  hr_payroll_account_operating_unit/models/hr_payslip.py
  hr_payroll_account_operating_unit/readme/CONTRIBUTORS.rst
  hr_payroll_account_operating_unit/readme/DESCRIPTION.rst
  hr_payroll_account_operating_unit/static/description/icon.png
  hr_payroll_account_operating_unit/static/description/index.html
  hr_payroll_account_operating_unit/tests/__init__.py
  hr_payroll_account_operating_unit/tests/test_payroll_account_operating_unit.py
  setup/hr_payroll_account_operating_unit/odoo/addons/hr_payroll_account_operating_unit
  setup/hr_payroll_account_operating_unit/setup.py
Labels: approved, bot is merging ⏳

#512 [FIX][14.0] operating unit: #503
  operating_unit/models/res_users.py
Labels: approved, ready to merge, bot is merging ⏳

#409 [14.0][MIG] mail_template_operating_unit
  mail_template_operating_unit/README.rst
  mail_template_operating_unit/__init__.py
  mail_template_operating_unit/__manifest__.py
  mail_template_operating_unit/models/__init__.py
  mail_template_operating_unit/models/mail.py
  mail_template_operating_unit/readme/CONTRIBUTORS.rst
  mail_template_operating_unit/readme/DESCRIPTION.rst
  mail_template_operating_unit/readme/USAGE.rst
  mail_template_operating_unit/security/mail_security.xml
  mail_template_operating_unit/static/description/icon.png
  mail_template_operating_unit/static/description/index.html
  mail_template_operating_unit/views/mail_template_view.xml
  setup/mail_template_operating_unit/odoo/addons/mail_template_operating_unit
  setup/mail_template_operating_unit/setup.py
Labels: approved, migration, bot is merging ⏳

#464 [14.0][MIG] sale_operating_unit
  sale_operating_unit/README.rst
  sale_operating_unit/__init__.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/i18n/sale_operating_unit.pot
  sale_operating_unit/models/__init__.py
  sale_operating_unit/models/crm_team.py
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/readme/CONTRIBUTORS.rst
  sale_operating_unit/readme/DESCRIPTION.rst
  sale_operating_unit/readme/ROADMAP.rst
  sale_operating_unit/readme/USAGE.rst
  sale_operating_unit/report/__init__.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/security/sale_security.xml
  sale_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/index.html
  sale_operating_unit/tests/__init__.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_operating_unit/views/sale_report_view.xml
  sale_operating_unit/views/sale_view.xml
  sale_operating_unit/wizard/__init__.py
  sale_operating_unit/wizard/sale_make_invoice_advance.py
  setup/sale_operating_unit/odoo/addons/sale_operating_unit
  setup/sale_operating_unit/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#514 [15.0][FIX] operation_unit: fix acces not applied
  operating_unit/models/res_users.py
Labels: bot is merging ⏳

#457 [14.0][IMP]account_operating_unit: Improve the xpath of Invoice line analytic_account_id
  account_operating_unit/views/account_move_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#387 [14.0][MIG from v9] purchase_request_to_requisition_operating_unit
  purchase_request_to_requisition_operating_unit/__init__.py
  purchase_request_to_requisition_operating_unit/__manifest__.py
  purchase_request_to_requisition_operating_unit/readme/CONTRIBUTORS.rst
  purchase_request_to_requisition_operating_unit/readme/DESCRIPTION.rst
  purchase_request_to_requisition_operating_unit/static/description/icon.png
  purchase_request_to_requisition_operating_unit/tests/__init__.py
  purchase_request_to_requisition_operating_unit/tests/test_purchase_request_to_requisition_operating_unit.py
  purchase_request_to_requisition_operating_unit/wizard/__init__.py
  purchase_request_to_requisition_operating_unit/wizard/purchase_request_line_make_purchase_requisition.py
  setup/purchase_request_to_requisition_operating_unit/odoo/addons/purchase_request_to_requisition_operating_unit
  setup/purchase_request_to_requisition_operating_unit/setup.py
Labels: approved, ready to merge, bot is merging ⏳
