Repository OCA/operating-unit, pull requests merged in 2023-05, with the labels that each got.

#574 [15.0][MIG] hr_expense_operating_unit
  hr_expense_operating_unit/README.rst
  hr_expense_operating_unit/__init__.py
  hr_expense_operating_unit/__manifest__.py
  hr_expense_operating_unit/i18n/hr_expense_operating_unit.pot
  hr_expense_operating_unit/models/__init__.py
  hr_expense_operating_unit/models/hr_expense.py
  hr_expense_operating_unit/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit/readme/DESCRIPTION.rst
  hr_expense_operating_unit/readme/USAGE.rst
  hr_expense_operating_unit/security/hr_expense_security.xml
  hr_expense_operating_unit/static/description/icon.png
  hr_expense_operating_unit/static/description/index.html
  hr_expense_operating_unit/tests/__init__.py
  hr_expense_operating_unit/tests/test_hr_expense_operating_unit.py
  hr_expense_operating_unit/views/hr_expense_view.xml
  hr_expense_operating_unit/wizards/__init__.py
  hr_expense_operating_unit/wizards/account_payment_register.py
  setup/hr_expense_operating_unit/odoo/addons/hr_expense_operating_unit
  setup/hr_expense_operating_unit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#563 [15.0][mig]-report_qweb_operating_unit
  report_qweb_operating_unit/README.rst
  report_qweb_operating_unit/__init__.py
  report_qweb_operating_unit/__manifest__.py
  report_qweb_operating_unit/i18n/es_MX.po
  report_qweb_operating_unit/i18n/report_qweb_operating_unit.pot
  report_qweb_operating_unit/readme/CONTRIBUTORS.rst
  report_qweb_operating_unit/readme/DESCRIPTION.rst
  report_qweb_operating_unit/static/description/icon.png
  report_qweb_operating_unit/static/description/index.html
  report_qweb_operating_unit/views/report_qweb_operating_unit.xml
  setup/report_qweb_operating_unit/odoo/addons/report_qweb_operating_unit
  setup/report_qweb_operating_unit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#531 [15.0][MIG] account_financial_report_operating_unit: Migration to 15.0
  account_financial_report_operating_unit/README.rst
  account_financial_report_operating_unit/__init__.py
  account_financial_report_operating_unit/__manifest__.py
  account_financial_report_operating_unit/i18n/account_financial_report_operating_unit.pot
  account_financial_report_operating_unit/readme/CONTRIBUTORS.rst
  account_financial_report_operating_unit/readme/DESCRIPTION.rst
  account_financial_report_operating_unit/report/__init__.py
  account_financial_report_operating_unit/report/aged_partner_balance.py
  account_financial_report_operating_unit/report/general_ledger.py
  account_financial_report_operating_unit/report/journal_ledger.py
  account_financial_report_operating_unit/report/open_items.py
  account_financial_report_operating_unit/report/trial_balance.py
  account_financial_report_operating_unit/report/vat_report.py
  account_financial_report_operating_unit/static/description/icon.png
  account_financial_report_operating_unit/static/description/index.html
  account_financial_report_operating_unit/wizards/__init__.py
  account_financial_report_operating_unit/wizards/aged_partner_balance_wizard.py
  account_financial_report_operating_unit/wizards/aged_partner_balance_wizard_view.xml
  account_financial_report_operating_unit/wizards/general_ledger_wizard.py
  account_financial_report_operating_unit/wizards/general_ledger_wizard_view.xml
  account_financial_report_operating_unit/wizards/journal_ledger_wizard.py
  account_financial_report_operating_unit/wizards/journal_ledger_wizard_view.xml
  account_financial_report_operating_unit/wizards/open_items_wizard.py
  account_financial_report_operating_unit/wizards/open_items_wizard_view.xml
  account_financial_report_operating_unit/wizards/trial_balance_wizard.py
  account_financial_report_operating_unit/wizards/trial_balance_wizard_view.xml
  account_financial_report_operating_unit/wizards/vat_report_wizard.py
  account_financial_report_operating_unit/wizards/vat_report_wizard_view.xml
  setup/account_financial_report_operating_unit/odoo/addons/account_financial_report_operating_unit
  setup/account_financial_report_operating_unit/setup.py
Labels: approved, bot is merging ⏳

#589 [15.0][MIG] stock_operating_unit_access_all
  setup/stock_operating_unit_access_all/odoo/addons/stock_operating_unit_access_all
  setup/stock_operating_unit_access_all/setup.py
  stock_operating_unit_access_all/README.rst
  stock_operating_unit_access_all/__init__.py
  stock_operating_unit_access_all/__manifest__.py
  stock_operating_unit_access_all/i18n/stock_operating_unit_access_all.pot
  stock_operating_unit_access_all/readme/CONFIGURE.rst
  stock_operating_unit_access_all/readme/CONTRIBUTORS.rst
  stock_operating_unit_access_all/readme/DESCRIPTION.rst
  stock_operating_unit_access_all/security/stock_security.xml
  stock_operating_unit_access_all/static/description/icon.png
  stock_operating_unit_access_all/static/description/index.html
Labels: approved, bot is merging ⏳

#588 [15.0][MIG] hr_expense_operating_unit_access_all
  hr_expense_operating_unit_access_all/README.rst
  hr_expense_operating_unit_access_all/__init__.py
  hr_expense_operating_unit_access_all/__manifest__.py
  hr_expense_operating_unit_access_all/i18n/hr_expense_operating_unit_access_all.pot
  hr_expense_operating_unit_access_all/readme/CONFIGURE.rst
  hr_expense_operating_unit_access_all/readme/CONTRIBUTORS.rst
  hr_expense_operating_unit_access_all/readme/DESCRIPTION.rst
  hr_expense_operating_unit_access_all/security/hr_expense_security.xml
  hr_expense_operating_unit_access_all/static/description/icon.png
  hr_expense_operating_unit_access_all/static/description/index.html
  setup/hr_expense_operating_unit_access_all/odoo/addons/hr_expense_operating_unit_access_all
  setup/hr_expense_operating_unit_access_all/setup.py
Labels: approved, bot is merging ⏳

#590 [15.0][FIX] stock_operating_unit: migration script to 15.0
  stock_operating_unit/migrations/15.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳

#587 [15.0][MIG] mis_builder_operating_unit
  mis_builder_operating_unit/README.rst
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/i18n/da.po
  mis_builder_operating_unit/i18n/it.po
  mis_builder_operating_unit/i18n/mis_builder_operating_unit.pot
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/readme/CONTRIBUTORS.rst
  mis_builder_operating_unit/readme/DESCRIPTION.rst
  mis_builder_operating_unit/readme/USAGE.rst
  mis_builder_operating_unit/security/mis_builder_security.xml
  mis_builder_operating_unit/static/description/icon.png
  mis_builder_operating_unit/static/description/index.html
  mis_builder_operating_unit/view/mis_builder.xml
  setup/mis_builder_operating_unit/odoo/addons/mis_builder_operating_unit
  setup/mis_builder_operating_unit/setup.py
Labels: approved, bot is merging ⏳
