Repository OCA/operating-unit, pull requests merged in 2023-08, with the labels that each got.

#613 [16.0] Migration of sales_team_operating unit
  sales_team_operating_unit/README.rst
  sales_team_operating_unit/__init__.py
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/i18n/es_AR.po
  sales_team_operating_unit/i18n/es_MX.po
  sales_team_operating_unit/i18n/sales_team_operating_unit.pot
  sales_team_operating_unit/models/__init__.py
  sales_team_operating_unit/models/crm_team.py
  sales_team_operating_unit/readme/CONTRIBUTORS.rst
  sales_team_operating_unit/readme/DESCRIPTION.rst
  sales_team_operating_unit/readme/USAGE.rst
  sales_team_operating_unit/security/crm_security.xml
  sales_team_operating_unit/static/description/icon.png
  sales_team_operating_unit/static/description/index.html
  sales_team_operating_unit/tests/__init__.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  sales_team_operating_unit/views/crm_team_view.xml
  setup/sales_team_operating_unit/odoo/addons/sales_team_operating_unit
  setup/sales_team_operating_unit/setup.py
Labels: approved, bot is merging ⏳

#616 [15.0][FIX] account_operating_unit: domain analytic from operating unit line
  account_operating_unit/views/account_move_view.xml
Labels: bot is merging ⏳

#577 [15.0][MIG] project_operating_unit: migration to 15.0
  project_operating_unit/README.rst
  project_operating_unit/__init__.py
  project_operating_unit/__manifest__.py
  project_operating_unit/i18n/project_operating_unit.pot
  project_operating_unit/i18n/pt.po
  project_operating_unit/models/__init__.py
  project_operating_unit/models/project_project.py
  project_operating_unit/models/project_task.py
  project_operating_unit/readme/CONTRIBUTORS.rst
  project_operating_unit/readme/CREDITS.rst
  project_operating_unit/readme/DESCRIPTION.rst
  project_operating_unit/readme/USAGE.rst
  project_operating_unit/security/project_security.xml
  project_operating_unit/static/description/icon.png
  project_operating_unit/static/description/index.html
  project_operating_unit/tests/__init__.py
  project_operating_unit/tests/test_project_operating_unit.py
  project_operating_unit/views/project_project.xml
  project_operating_unit/views/project_task.xml
  setup/project_operating_unit/odoo/addons/project_operating_unit
  setup/project_operating_unit/setup.py
Labels: approved, bot is merging ⏳, no stale

#591 [16.0] [MIG] product_operating_unit
  product_operating_unit/README.rst
  product_operating_unit/__init__.py
  product_operating_unit/__manifest__.py
  product_operating_unit/i18n/product_operating_unit.pot
  product_operating_unit/i18n/pt.po
  product_operating_unit/models/__init__.py
  product_operating_unit/models/product_category.py
  product_operating_unit/models/product_template.py
  product_operating_unit/readme/CONTRIBUTORS.rst
  product_operating_unit/readme/DESCRIPTION.rst
  product_operating_unit/readme/ROADMAP.rst
  product_operating_unit/readme/USAGE.rst
  product_operating_unit/security/product_template_security.xml
  product_operating_unit/static/description/icon.png
  product_operating_unit/static/description/index.html
  product_operating_unit/tests/__init__.py
  product_operating_unit/tests/test_product_operating_unit.py
  product_operating_unit/views/product_category_view.xml
  product_operating_unit/views/product_template_view.xml
  setup/product_operating_unit/odoo/addons/product_operating_unit
  setup/product_operating_unit/setup.py
Labels: bot is merging ⏳

#598 [16.0] [MIG] stock_operating_unit
  setup/stock_operating_unit/odoo/addons/stock_operating_unit
  setup/stock_operating_unit/setup.py
  stock_operating_unit/README.rst
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/data/stock_data.xml
  stock_operating_unit/demo/stock_demo.xml
  stock_operating_unit/i18n/es_AR.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/model/__init__.py
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_move.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_quant.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/readme/CONFIGURE.rst
  stock_operating_unit/readme/CONTRIBUTORS.rst
  stock_operating_unit/readme/DESCRIPTION.rst
  stock_operating_unit/readme/ROADMAP.rst
  stock_operating_unit/readme/USAGE.rst
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/index.html
  stock_operating_unit/tests/__init__.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
  stock_operating_unit/view/stock.xml
Labels: approved, bot is merging ⏳
