Repository OCA/operating-unit, pull requests merged in 2023-09, with the labels that each got.

#606 [15.0][ADD] mrp_operating_unit_access_all
  mrp_operating_unit_access_all/README.rst
  mrp_operating_unit_access_all/__init__.py
  mrp_operating_unit_access_all/__manifest__.py
  mrp_operating_unit_access_all/readme/CONFIGURE.rst
  mrp_operating_unit_access_all/readme/CONTRIBUTORS.rst
  mrp_operating_unit_access_all/readme/DESCRIPTION.rst
  mrp_operating_unit_access_all/security/mrp_security.xml
  mrp_operating_unit_access_all/static/description/icon.png
  mrp_operating_unit_access_all/static/description/index.html
  setup/mrp_operating_unit_access_all/odoo/addons/mrp_operating_unit_access_all
  setup/mrp_operating_unit_access_all/setup.py
Labels: approved, bot is merging ⏳

#549 [15.0][ADD] hr_operating_unit_access_all
  hr_operating_unit_access_all/README.rst
  hr_operating_unit_access_all/__init__.py
  hr_operating_unit_access_all/__manifest__.py
  hr_operating_unit_access_all/readme/CONFIGURE.rst
  hr_operating_unit_access_all/readme/CONTRIBUTORS.rst
  hr_operating_unit_access_all/readme/DESCRIPTION.rst
  hr_operating_unit_access_all/security/hr_security.xml
  hr_operating_unit_access_all/static/description/icon.png
  hr_operating_unit_access_all/static/description/index.html
  setup/hr_operating_unit_access_all/odoo/addons/hr_operating_unit_access_all
  setup/hr_operating_unit_access_all/setup.py
Labels: approved, bot is merging ⏳, stale

#608 [15.0][FIX] stock_operating_unit_access_all: domain_force in stock move is not correct
  stock_operating_unit_access_all/readme/CONTRIBUTORS.rst
  stock_operating_unit_access_all/security/stock_security.xml
Labels: approved, ready to merge, bot is merging ⏳

#619 [15.0][FIX] stock_operating_unit: access to picking types when warehouse is not set
  stock_operating_unit/security/stock_security.xml
Labels: approved, bot is merging ⏳

#620 [FWD][16.0][FIX] stock_operating_unit: access to picking types when warehouse is not set
  stock_operating_unit/security/stock_security.xml
Labels: bot is merging ⏳

#610 [15.0][FIX] account_operating_unit: assign operating unit of the invoice journal has no operating unit no matter if OU are self balanced
  account_operating_unit/models/account_payment.py
Labels: approved, ready to merge, bot is merging ⏳

#609 [13.0][IMP] account_operating_unit: added migration scripts
  account_operating_unit/migrations/13.0.1.0.0/post-migration.py
Labels: approved, bot is merging ⏳
