Repository OCA/operating-unit, pull requests merged in 2023-01, with the labels that each got.

#494 15.0][MIG] operating_unit_access_all: Migration to 15.0
  operating_unit_access_all/README.rst
  operating_unit_access_all/__init__.py
  operating_unit_access_all/__manifest__.py
  operating_unit_access_all/i18n/operating_unit_access_all.pot
  operating_unit_access_all/readme/CONFIGURE.rst
  operating_unit_access_all/readme/CONTRIBUTORS.rst
  operating_unit_access_all/readme/DESCRIPTION.rst
  operating_unit_access_all/security/operating_unit_security.xml
  operating_unit_access_all/static/description/icon.png
  operating_unit_access_all/static/description/index.html
  setup/operating_unit_access_all/odoo/addons/operating_unit_access_all
  setup/operating_unit_access_all/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#522 [15.0][MIG] account_operating_unit
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/models/__init__.py
  account_operating_unit/models/account_bank_statement.py
  account_operating_unit/models/account_journal.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_partial_reconcile.py
  account_operating_unit/models/account_payment.py
  account_operating_unit/models/res_company.py
  account_operating_unit/readme/CONFIGURE.rst
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/readme/DESCRIPTION.rst
  account_operating_unit/readme/ROADMAP.rst
  account_operating_unit/readme/USAGE.rst
  account_operating_unit/report/__init__.py
  account_operating_unit/report/account_invoice_report.py
  account_operating_unit/security/account_security.xml
  account_operating_unit/static/description/icon.png
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/__init__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/views/account_invoice_report_view.xml
  account_operating_unit/views/account_journal_view.xml
  account_operating_unit/views/account_move_view.xml
  account_operating_unit/views/account_payment_view.xml
  account_operating_unit/views/company_view.xml
  account_operating_unit/wizards/__init__.py
  account_operating_unit/wizards/account_payment_register.py
  setup/account_operating_unit/odoo/addons/account_operating_unit
  setup/account_operating_unit/setup.py
Labels: approved, bot is merging ⏳

#521 [14.0][ADD] pos_operating_unit
  pos_operating_unit/README.rst
  pos_operating_unit/__init__.py
  pos_operating_unit/__manifest__.py
  pos_operating_unit/models/__init__.py
  pos_operating_unit/models/pos_config.py
  pos_operating_unit/models/pos_order.py
  pos_operating_unit/models/pos_payment.py
  pos_operating_unit/models/pos_session.py
  pos_operating_unit/readme/CONTRIBUTORS.rst
  pos_operating_unit/readme/DESCRIPTION.rst
  pos_operating_unit/readme/ROADMAP.rst
  pos_operating_unit/readme/USAGE.rst
  pos_operating_unit/security/pos_security.xml
  pos_operating_unit/static/description/icon.png
  pos_operating_unit/tests/__init__.py
  pos_operating_unit/tests/test_module.py
  pos_operating_unit/views/pos_views.xml
  setup/pos_operating_unit/odoo/addons/pos_operating_unit
  setup/pos_operating_unit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#525 [15.0][IMP] operating_unit: updated validation
  operating_unit/models/res_users.py
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/res_users_view.xml
Labels: bot is merging ⏳

#482 [15.0][MIG] mrp_operating_unit
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/readme/CONTRIBUTORS.rst
  mrp_operating_unit/readme/DESCRIPTION.rst
  mrp_operating_unit/readme/USAGE.rst
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
  setup/mrp_operating_unit/odoo/addons/mrp_operating_unit
  setup/mrp_operating_unit/setup.py
Labels: approved, ready to merge, bot is merging ⏳, no stale

#524 [14.0][FIX] OperatingUnit.name_search() omits args domain in "other search"
  operating_unit/models/operating_unit.py
Labels: approved, bot is merging ⏳

#481 [15.0][MIG] hr_contract_operating_unit
  hr_contract_operating_unit/README.rst
  hr_contract_operating_unit/__init__.py
  hr_contract_operating_unit/__manifest__.py
  hr_contract_operating_unit/i18n/hr_contract_operating_unit.pot
  hr_contract_operating_unit/i18n/pt.po
  hr_contract_operating_unit/models/__init__.py
  hr_contract_operating_unit/models/hr_contract.py
  hr_contract_operating_unit/readme/CONTRIBUTORS.rst
  hr_contract_operating_unit/readme/DESCRIPTION.rst
  hr_contract_operating_unit/readme/USAGE.rst
  hr_contract_operating_unit/security/hr_contract_security.xml
  hr_contract_operating_unit/static/description/icon.png
  hr_contract_operating_unit/static/description/index.html
  hr_contract_operating_unit/tests/__init__.py
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  hr_contract_operating_unit/views/hr_contract_view.xml
  setup/hr_contract_operating_unit/odoo/addons/hr_contract_operating_unit
  setup/hr_contract_operating_unit/setup.py
Labels: approved, bot is merging ⏳, no stale

#526 [14.0][FIX]operating_unit: while I access user record the faced the operating units access error
  operating_unit/models/res_users.py
Labels: bot is merging ⏳

#530 [15.0][FWD][FIX]operating_unit: while I access user record the faced the oprating units access error
  operating_unit/models/res_users.py
Labels: bot is merging ⏳

#533 [14.0] Fix org slug in repo config
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
Labels: bot is merging ⏳

#528 [15.0] [MIG] Migrated crm_operating_unit
  crm_operating_unit/README.rst
  crm_operating_unit/__init__.py
  crm_operating_unit/__manifest__.py
  crm_operating_unit/i18n/crm_operating_unit.pot
  crm_operating_unit/i18n/es.po
  crm_operating_unit/i18n/es_MX.po
  crm_operating_unit/i18n/fr.po
  crm_operating_unit/models/__init__.py
  crm_operating_unit/models/crm_lead.py
  crm_operating_unit/readme/CONTRIBUTORS.rst
  crm_operating_unit/readme/DESCRIPTION.rst
  crm_operating_unit/readme/USAGE.rst
  crm_operating_unit/security/crm_security.xml
  crm_operating_unit/static/description/icon.png
  crm_operating_unit/static/description/index.html
  crm_operating_unit/tests/__init__.py
  crm_operating_unit/tests/test_crm_operating_unit.py
  crm_operating_unit/views/crm_lead_view.xml
  setup/crm_operating_unit/odoo/addons/crm_operating_unit
  setup/crm_operating_unit/setup.py
Labels: bot is merging ⏳

#535 [15.0][FIX]-account_operating_unit: fix the error 'You are trying to …
  account_operating_unit/readme/CONTRIBUTORS.rst
  account_operating_unit/wizards/account_payment_register.py
Labels: approved, ready to merge, bot is merging ⏳

#539 [15.0][FIX] analytic operating unit: domain ou in users
  analytic_operating_unit/models/account_analytic_account.py
Labels: approved, bot is merging ⏳

#540 [FIX] 14.0 sale_operating_unit Error sale report to add fiel operating unit
  sale_operating_unit/README.rst
  sale_operating_unit/report/sale_report.py
Labels: approved, bot is merging ⏳

#543 [13.0][IMP] copier & pre-commit
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  mis_builder_budget_operating_unit/__manifest__.py
  mis_builder_budget_operating_unit/models/mis_budget_item.py
  mis_builder_operating_unit/__init__.py
  mis_builder_operating_unit/__manifest__.py
  mis_builder_operating_unit/model/__init__.py
  mis_builder_operating_unit/model/mis_builder.py
  mis_builder_operating_unit/tests/__init__.py
  mis_builder_operating_unit/tests/test_mis_builder_operating_unit.py
  mrp_operating_unit/__manifest__.py
  report_qweb_operating_unit/__manifest__.py
Labels: bot is merging ⏳

#542 [14.0][FIX] analytic_operating_unit: Error when search operating units in analytic account (& several forward ports)
  analytic_operating_unit/models/account_analytic_account.py
  operating_unit/demo/operating_unit_demo.xml
Labels: bot is merging ⏳

#541 [13.0][FIX] analytic_operating_unit: Error when search operating units in analytic account (& several backports)
  analytic_operating_unit/models/account_analytic_account.py
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/readme/CONTRIBUTORS.rst
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/res_users_view.xml
Labels: bot is merging ⏳

#544 [15.0][FIX] operating_nit: some forward ports
  hr_contract_operating_unit/tests/test_hr_contract_operating_unit.py
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/tests/test_operating_unit.py
Labels: bot is merging ⏳

#545 [14.0][FIX] operating_unit: minor fix in test
  operating_unit/tests/test_operating_unit.py
Labels: bot is merging ⏳

#546 [15.0][UPD] copier & pre-commit
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#547 [16.0][UPD] copier & pre-commit
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#548 [15.0][MIG] hr_operating_unit
  hr_operating_unit/README.rst
  hr_operating_unit/__init__.py
  hr_operating_unit/__manifest__.py
  hr_operating_unit/i18n/es.po
  hr_operating_unit/i18n/fr.po
  hr_operating_unit/i18n/hr_operating_unit.pot
  hr_operating_unit/models/__init__.py
  hr_operating_unit/models/hr_employee_base.py
  hr_operating_unit/models/hr_operating_unit.py
  hr_operating_unit/readme/CONTRIBUTORS.rst
  hr_operating_unit/readme/DESCRIPTION.rst
  hr_operating_unit/readme/USAGE.rst
  hr_operating_unit/security/security.xml
  hr_operating_unit/static/description/icon.png
  hr_operating_unit/static/description/index.html
  hr_operating_unit/views/hr_employee.xml
  setup/hr_operating_unit/odoo/addons/hr_operating_unit
  setup/hr_operating_unit/setup.py
Labels: bot is merging ⏳
