Repository OCA/operating-unit, pull requests merged in 2023-03, with the labels that each got.

#565 [15.0][FIX] account_operating_unit: re reconcile payment for case self balance only
  account_operating_unit/wizards/account_payment_register.py
Labels: approved, bot is merging ⏳

#567 [15.0][FIX] stock_operating_unit: filter domain users out
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/view/stock.xml
Labels: approved, bot is merging ⏳

#569 [15.0][MIG] purchase_operating_unit
  purchase_operating_unit/README.rst
  purchase_operating_unit/__init__.py
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/demo/purchase_order_demo.xml
  purchase_operating_unit/i18n/purchase_operating_unit.pot
  purchase_operating_unit/models/__init__.py
  purchase_operating_unit/models/account_move.py
  purchase_operating_unit/models/purchase_order.py
  purchase_operating_unit/readme/CONTRIBUTORS.rst
  purchase_operating_unit/readme/DESCRIPTION.rst
  purchase_operating_unit/readme/USAGE.rst
  purchase_operating_unit/security/purchase_security.xml
  purchase_operating_unit/static/description/icon.png
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/tests/__init__.py
  purchase_operating_unit/tests/test_po_security.py
  purchase_operating_unit/tests/test_purchase_operating_unit.py
  purchase_operating_unit/views/purchase_order_line_view.xml
  purchase_operating_unit/views/purchase_order_view.xml
  setup/purchase_operating_unit/odoo/addons/purchase_operating_unit
  setup/purchase_operating_unit/setup.py
Labels: approved, bot is merging ⏳

#570 [14.0][FIX]account_operating_unit: Ensure active_model is account.move before attempting to browse
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  .t2d.yml
  account_operating_unit/models/account_payment.py
Labels: bot is merging ⏳

#572 [15.0][FIX] stock_operating_unit: remove domain of operation type
  stock_operating_unit/view/stock.xml
Labels: approved, bot is merging ⏳

#555 [15.0][MIG] account_asset_operating_unit
  account_asset_operating_unit/README.rst
  account_asset_operating_unit/__init__.py
  account_asset_operating_unit/__manifest__.py
  account_asset_operating_unit/i18n/account_asset_operating_unit.pot
  account_asset_operating_unit/models/__init__.py
  account_asset_operating_unit/models/account_asset.py
  account_asset_operating_unit/models/account_asset_line.py
  account_asset_operating_unit/models/account_move.py
  account_asset_operating_unit/readme/CONTRIBUTORS.rst
  account_asset_operating_unit/readme/DESCRIPTION.rst
  account_asset_operating_unit/readme/USAGE.rst
  account_asset_operating_unit/report/__init__.py
  account_asset_operating_unit/report/account_asset_report_xls.py
  account_asset_operating_unit/security/account_asset_security.xml
  account_asset_operating_unit/static/description/icon.png
  account_asset_operating_unit/static/description/index.html
  account_asset_operating_unit/tests/__init__.py
  account_asset_operating_unit/tests/test_account_asset_operating_unit.py
  account_asset_operating_unit/views/account_asset_views.xml
  account_asset_operating_unit/wizard/__init__.py
  account_asset_operating_unit/wizard/account_asset_remove.py
  account_asset_operating_unit/wizard/wiz_account_asset_report.py
  account_asset_operating_unit/wizard/wiz_account_asset_report.xml
  setup/account_asset_operating_unit/odoo/addons/account_asset_operating_unit
  setup/account_asset_operating_unit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#573 [15.0][FIX] account_operating_unit: add OU to tree view of account.move.line
  account_operating_unit/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#499 [14.0][FIX] account_asset_operating_unit: fix reporting by OU
  account_asset_operating_unit/report/account_asset_report_xls.py
  account_asset_operating_unit/tests/test_account_asset_operating_unit.py
Labels: approved, ready to merge, bot is merging ⏳

#575 [15.0][MIG] purchase_request_operating_unit
  purchase_request_operating_unit/README.rst
  purchase_request_operating_unit/__init__.py
  purchase_request_operating_unit/__manifest__.py
  purchase_request_operating_unit/i18n/fr.po
  purchase_request_operating_unit/i18n/pt.po
  purchase_request_operating_unit/i18n/purchase_request_operating_unit.pot
  purchase_request_operating_unit/model/__init__.py
  purchase_request_operating_unit/model/purchase_request.py
  purchase_request_operating_unit/readme/CONTRIBUTORS.rst
  purchase_request_operating_unit/readme/DESCRIPTION.rst
  purchase_request_operating_unit/readme/USAGE.rst
  purchase_request_operating_unit/security/purchase_security.xml
  purchase_request_operating_unit/static/description/icon.png
  purchase_request_operating_unit/static/description/index.html
  purchase_request_operating_unit/test-requirements.txt
  purchase_request_operating_unit/tests/__init__.py
  purchase_request_operating_unit/tests/test_purchase_request_operating_unit.py
  purchase_request_operating_unit/tests/test_purchase_request_to_rfq_operating_unit.py
  purchase_request_operating_unit/view/purchase_request_view.xml
  purchase_request_operating_unit/wizard/__init__.py
  purchase_request_operating_unit/wizard/purchase_request_line_make_purchase_order.py
  purchase_request_operating_unit/wizard/purchase_request_line_make_purchase_order_view.xml
  setup/purchase_request_operating_unit/odoo/addons/purchase_request_operating_unit
  setup/purchase_request_operating_unit/setup.py
Labels: approved, bot is merging ⏳
