Repository OCA/operating-unit, pull requests merged in 2024-01, with the labels that each got.

#642 [14.0][FIX] operating_unit: default operating unit more multi-company friendly
  operating_unit/models/res_users.py
  operating_unit/tests/test_operating_unit.py
  product_operating_unit/models/product_template.py
Labels: approved, ready to merge, bot is merging ⏳

#643 [15.0][FW][FIX] operating_unit: default operating unit more multi-company friendly
  operating_unit/models/res_users.py
  operating_unit/tests/test_operating_unit.py
Labels: bot is merging ⏳

#644 [16.0][FW][FIX] operating_unit: default operating unit more multi-company friendly
  operating_unit/models/res_users.py
  operating_unit/tests/test_operating_unit.py
  product_operating_unit/models/product_template.py
Labels: bot is merging ⏳

#647 [14.0][FIX] purchase_operating_unit: default picking_type without OU
  purchase_operating_unit/models/purchase_order.py
Labels: approved, bot is merging ⏳

#537 [15.0][MIG] contract_operating_unit: Migration to 15.0
  contract_operating_unit/README.rst
  contract_operating_unit/__init__.py
  contract_operating_unit/__manifest__.py
  contract_operating_unit/i18n/contract_operating_unit.pot
  contract_operating_unit/models/__init__.py
  contract_operating_unit/models/contract.py
  contract_operating_unit/readme/CONTRIBUTORS.rst
  contract_operating_unit/readme/DESCRIPTION.rst
  contract_operating_unit/readme/USAGE.rst
  contract_operating_unit/security/contract_security.xml
  contract_operating_unit/static/description/icon.png
  contract_operating_unit/static/description/index.html
  contract_operating_unit/tests/__init__.py
  contract_operating_unit/tests/test_contract_operating_unit.py
  contract_operating_unit/views/contract_view.xml
  setup/contract_operating_unit/odoo/addons/contract_operating_unit
  setup/contract_operating_unit/setup.py
Labels: approved, bot is merging ⏳, no stale

#648 [15.0][FIX] purchase_request_operating_unit: respect original domain
  purchase_request_operating_unit/wizard/purchase_request_line_make_purchase_order_view.xml
Labels: approved, bot is merging ⏳
