Repository OCA/operating-unit, pull requests merged in 2024-07, with the labels that each got.

#667 [MIG] operating_unit: Migration to 17.0
  operating_unit/README.rst
  operating_unit/__init__.py
  operating_unit/__manifest__.py
  operating_unit/data/operating_unit_data.xml
  operating_unit/demo/operating_unit_demo.xml
  operating_unit/i18n/es_AR.po
  operating_unit/i18n/es_MX.po
  operating_unit/i18n/operating_unit.pot
  operating_unit/models/__init__.py
  operating_unit/models/ir_rule.py
  operating_unit/models/operating_unit.py
  operating_unit/models/res_users.py
  operating_unit/pyproject.toml
  operating_unit/readme/CONFIGURE.md
  operating_unit/readme/CONTRIBUTORS.md
  operating_unit/readme/DESCRIPTION.md
  operating_unit/readme/ROADMAP.md
  operating_unit/readme/USAGE.md
  operating_unit/security/ir.model.access.csv
  operating_unit/security/operating_unit_security.xml
  operating_unit/static/description/icon.png
  operating_unit/static/description/index.html
  operating_unit/tests/__init__.py
  operating_unit/tests/common.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/operating_unit_view.xml
  operating_unit/view/res_users_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#669 [MIG] analytic_operating_unit: Migration to 17.0
  analytic_operating_unit/README.rst
  analytic_operating_unit/__init__.py
  analytic_operating_unit/__manifest__.py
  analytic_operating_unit/i18n/analytic_operating_unit.pot
  analytic_operating_unit/i18n/es_AR.po
  analytic_operating_unit/i18n/es_MX.po
  analytic_operating_unit/i18n/it.po
  analytic_operating_unit/models/__init__.py
  analytic_operating_unit/models/account_analytic_account.py
  analytic_operating_unit/pyproject.toml
  analytic_operating_unit/readme/CONTRIBUTORS.md
  analytic_operating_unit/readme/DESCRIPTION.md
  analytic_operating_unit/readme/USAGE.md
  analytic_operating_unit/security/analytic_account_security.xml
  analytic_operating_unit/static/description/icon.png
  analytic_operating_unit/static/description/index.html
  analytic_operating_unit/static/src/components/analytic_distribution.esm.js
  analytic_operating_unit/views/analytic_account_view.xml
Labels: approved, bot is merging ⏳

#671 [MIG] sales_team_operating_unit: Migration to 17.0
  sales_team_operating_unit/README.rst
  sales_team_operating_unit/__init__.py
  sales_team_operating_unit/__manifest__.py
  sales_team_operating_unit/i18n/es_AR.po
  sales_team_operating_unit/i18n/es_MX.po
  sales_team_operating_unit/i18n/it.po
  sales_team_operating_unit/i18n/sales_team_operating_unit.pot
  sales_team_operating_unit/models/__init__.py
  sales_team_operating_unit/models/crm_team.py
  sales_team_operating_unit/pyproject.toml
  sales_team_operating_unit/readme/CONTRIBUTORS.md
  sales_team_operating_unit/readme/DESCRIPTION.md
  sales_team_operating_unit/readme/USAGE.md
  sales_team_operating_unit/security/crm_security.xml
  sales_team_operating_unit/static/description/icon.png
  sales_team_operating_unit/static/description/index.html
  sales_team_operating_unit/tests/__init__.py
  sales_team_operating_unit/tests/test_crm_team_operating_unit.py
  sales_team_operating_unit/views/crm_team_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#668 [MIG] product_operating_unit: Migration to 17.0
  product_operating_unit/README.rst
  product_operating_unit/__init__.py
  product_operating_unit/__manifest__.py
  product_operating_unit/i18n/es.po
  product_operating_unit/i18n/it.po
  product_operating_unit/i18n/ja.po
  product_operating_unit/i18n/product_operating_unit.pot
  product_operating_unit/i18n/pt.po
  product_operating_unit/models/__init__.py
  product_operating_unit/models/product_category.py
  product_operating_unit/models/product_template.py
  product_operating_unit/pyproject.toml
  product_operating_unit/readme/CONTRIBUTORS.md
  product_operating_unit/readme/DESCRIPTION.md
  product_operating_unit/readme/ROADMAP.md
  product_operating_unit/readme/USAGE.md
  product_operating_unit/security/product_template_security.xml
  product_operating_unit/static/description/icon.png
  product_operating_unit/static/description/index.html
  product_operating_unit/tests/__init__.py
  product_operating_unit/tests/test_product_operating_unit.py
  product_operating_unit/views/product_category_view.xml
  product_operating_unit/views/product_template_view.xml
Labels: approved, bot is merging ⏳

#678 [17.0][MIG] `res_partner_operating_unit`: Migration to 17.0
  res_partner_operating_unit/README.rst
  res_partner_operating_unit/__init__.py
  res_partner_operating_unit/__manifest__.py
  res_partner_operating_unit/hooks.py
  res_partner_operating_unit/i18n/it.po
  res_partner_operating_unit/i18n/pt.po
  res_partner_operating_unit/i18n/res_partner_operating_unit.pot
  res_partner_operating_unit/models/__init__.py
  res_partner_operating_unit/models/res_partner.py
  res_partner_operating_unit/models/res_users.py
  res_partner_operating_unit/pyproject.toml
  res_partner_operating_unit/readme/CONTRIBUTORS.md
  res_partner_operating_unit/readme/CREDITS.md
  res_partner_operating_unit/readme/DESCRIPTION.md
  res_partner_operating_unit/readme/USAGE.md
  res_partner_operating_unit/security/res_partner_security.xml
  res_partner_operating_unit/static/description/icon.png
  res_partner_operating_unit/static/description/index.html
  res_partner_operating_unit/tests/__init__.py
  res_partner_operating_unit/tests/test_res_partner_operating_unit.py
  res_partner_operating_unit/views/res_partner_view.xml
  setup/res_partner_operating_unit/odoo/addons/res_partner_operating_unit
Labels: bot is merging ⏳

#687 [17.0][MIG] analytic_operating_unit_access_all: Migration to 17.0
  analytic_operating_unit_access_all/README.rst
  analytic_operating_unit_access_all/__init__.py
  analytic_operating_unit_access_all/__manifest__.py
  analytic_operating_unit_access_all/i18n/analytic_operating_unit_access_all.pot
  analytic_operating_unit_access_all/i18n/it.po
  analytic_operating_unit_access_all/pyproject.toml
  analytic_operating_unit_access_all/readme/CONFIGURE.md
  analytic_operating_unit_access_all/readme/CONTRIBUTORS.md
  analytic_operating_unit_access_all/readme/DESCRIPTION.md
  analytic_operating_unit_access_all/security/analytic_security.xml
  analytic_operating_unit_access_all/static/description/icon.png
  analytic_operating_unit_access_all/static/description/index.html
Labels: approved, bot is merging ⏳

#694 [17.0][MIG] project_operating_unit: Migration to 17.0
  project_operating_unit/README.rst
  project_operating_unit/__init__.py
  project_operating_unit/__manifest__.py
  project_operating_unit/i18n/it.po
  project_operating_unit/i18n/project_operating_unit.pot
  project_operating_unit/i18n/pt.po
  project_operating_unit/models/__init__.py
  project_operating_unit/models/project_project.py
  project_operating_unit/models/project_task.py
  project_operating_unit/pyproject.toml
  project_operating_unit/readme/CONTRIBUTORS.md
  project_operating_unit/readme/CREDITS.md
  project_operating_unit/readme/DESCRIPTION.md
  project_operating_unit/readme/USAGE.md
  project_operating_unit/security/project_security.xml
  project_operating_unit/static/description/icon.png
  project_operating_unit/static/description/index.html
  project_operating_unit/tests/__init__.py
  project_operating_unit/tests/test_project_operating_unit.py
  project_operating_unit/views/project_project.xml
  project_operating_unit/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳
