Repository OCA/operating-unit, pull requests merged in 2024-05, with the labels that each got.

#650 [15.0][FIX] hr_payroll_account_operating_unit: assign the operating unit to the payslip journal items
  hr_payroll_account_operating_unit/models/hr_payslip.py
Labels: approved, bot is merging ⏳

#660 [15.0] Remove unnecessary test-requirements.txt files
  purchase_request_operating_unit/test-requirements.txt
  stock_account_operating_unit/test-requirements.txt
Labels: bot is merging ⏳

#664 [14.0][FIX] purchase_operating_unit: Fix warning from an onchange function returning domain. Use domain fi…
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/models/account_invoice.py
  purchase_operating_unit/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#658 [15.0][IMP] account_operating_unit: allow to pay multiple invoices with different operating units
  account_operating_unit/__init__.py
  account_operating_unit/models/account_move.py
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/wizards/__init__.py
  account_operating_unit/wizards/account_payment_register.py
Labels: approved, ready to merge, bot is merging ⏳

#665 [15.0][FIX] purchase_operating_unit: Fix warning from an onchange function …
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/models/account_move.py
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#666 [14.0][FIX] purchase_operating_unit: depends from account_operating_unit
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳
