Repository OCA/operating-unit, pull requests merged in 2025-03, with the labels that each got.

#742 [18.0][MIG] stock_operating_unit_access_all : Migration to 18.0
  stock_operating_unit_access_all/README.rst
  stock_operating_unit_access_all/__init__.py
  stock_operating_unit_access_all/__manifest__.py
  stock_operating_unit_access_all/i18n/it.po
  stock_operating_unit_access_all/i18n/stock_operating_unit_access_all.pot
  stock_operating_unit_access_all/pyproject.toml
  stock_operating_unit_access_all/readme/CONFIGURE.md
  stock_operating_unit_access_all/readme/CONTRIBUTORS.md
  stock_operating_unit_access_all/readme/DESCRIPTION.md
  stock_operating_unit_access_all/security/stock_security.xml
  stock_operating_unit_access_all/static/description/icon.png
  stock_operating_unit_access_all/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#710 [17.0][FIX] contract_operating_unit - use same logic as other security rules
  contract_operating_unit/security/contract_security.xml
Labels: bot is merging ⏳

#722 [18.0][MIG] mrp_operating_unit: Migration to 18.0
  mrp_operating_unit/README.rst
  mrp_operating_unit/__init__.py
  mrp_operating_unit/__manifest__.py
  mrp_operating_unit/i18n/mrp_operating_unit.pot
  mrp_operating_unit/models/__init__.py
  mrp_operating_unit/models/mrp.py
  mrp_operating_unit/models/stock_rule.py
  mrp_operating_unit/pyproject.toml
  mrp_operating_unit/readme/CONTRIBUTORS.md
  mrp_operating_unit/readme/DESCRIPTION.md
  mrp_operating_unit/readme/USAGE.md
  mrp_operating_unit/security/mrp_security.xml
  mrp_operating_unit/static/description/icon.png
  mrp_operating_unit/static/description/index.html
  mrp_operating_unit/tests/__init__.py
  mrp_operating_unit/tests/test_mrp_operating_unit.py
  mrp_operating_unit/views/mrp_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#708 [16.0][FIX] account_operating_unit: do not show inter-OU balance journals as invoice lines
  account_operating_unit/__manifest__.py
  account_operating_unit/migrations/16.0.1.1.0/pre-migration.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_move_line.py
  account_operating_unit/static/description/index.html
  account_operating_unit/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳, no stale

#758 [16.0][FIX] account_operating_unit: set OU on exchange move/lines
  account_operating_unit/models/account_move_line.py
Labels: approved, bot is merging ⏳

#739 [17.0][FIX] account_operating_unit: do not show inter-OU balance journals as invoice lines
  account_operating_unit/__manifest__.py
  account_operating_unit/migrations/17.0.1.1.0/pre-migration.py
  account_operating_unit/models/account_move.py
  account_operating_unit/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#751 [15.0][FIX] account_operating_unit: Inter OU Balance entry several issues
  account_operating_unit/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#760 [16.0][FWD][FIX] account_operating_unit: Inter OU Balance entry several issues
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_move_line.py
Labels: approved, bot is merging ⏳

#761 [17.0][FWD][FIX] account_operating_unit: Inter OU Balance entry several issues
  account_operating_unit/models/account_move.py
Labels: bot is merging ⏳
