Repository OCA/operating-unit, pull requests merged in 2025-02, with the labels that each got.

#721 [18.0][MIG] stock_operating_unit: Migration to 18.0
  stock_operating_unit/README.rst
  stock_operating_unit/__init__.py
  stock_operating_unit/__manifest__.py
  stock_operating_unit/data/stock_data.xml
  stock_operating_unit/demo/stock_demo.xml
  stock_operating_unit/i18n/es_AR.po
  stock_operating_unit/i18n/it.po
  stock_operating_unit/i18n/stock_operating_unit.pot
  stock_operating_unit/model/__init__.py
  stock_operating_unit/model/stock_location.py
  stock_operating_unit/model/stock_move.py
  stock_operating_unit/model/stock_picking.py
  stock_operating_unit/model/stock_quant.py
  stock_operating_unit/model/stock_rule.py
  stock_operating_unit/model/stock_warehouse.py
  stock_operating_unit/pyproject.toml
  stock_operating_unit/readme/CONFIGURE.md
  stock_operating_unit/readme/CONTRIBUTORS.md
  stock_operating_unit/readme/DESCRIPTION.md
  stock_operating_unit/readme/ROADMAP.md
  stock_operating_unit/readme/USAGE.md
  stock_operating_unit/security/stock_security.xml
  stock_operating_unit/static/description/icon.png
  stock_operating_unit/static/description/index.html
  stock_operating_unit/tests/__init__.py
  stock_operating_unit/tests/test_stock_operating_unit.py
  stock_operating_unit/tests/test_stock_picking.py
  stock_operating_unit/tests/test_stock_security.py
  stock_operating_unit/view/stock.xml
Labels: approved, ready to merge, bot is merging ⏳

#741 [14.0][FIX] stock_operating_unit: orderpoint OU check for ext locations
  stock_operating_unit/model/stock_warehouse.py
Labels: approved, bot is merging ⏳

#744 [16.0][FIX] stock_operating_unit: orderpoint OU check for ext locations
  stock_operating_unit/model/stock_warehouse.py
Labels: approved, bot is merging ⏳

#743 [15.0][FIX] stock_operating_unit: orderpoint OU check for ext locations
  stock_operating_unit/model/stock_warehouse.py
Labels: approved, bot is merging ⏳

#745 [17.0][FIX] stock_operating_unit: orderpoint OU check for ext locations
  stock_operating_unit/model/stock_warehouse.py
Labels: approved, bot is merging ⏳

#712 [17.0][FIX] account_financial_report_operating_unit - fix typo in the name of the module
  account_financial_report_operating_unit/README.rst
  account_financial_report_operating_unit/__manifest__.py
Labels: approved, bot is merging ⏳

#747 [15.0][FIX] account_financial_report_operating_unit - typo in module's name
  account_financial_report_operating_unit/README.rst
  account_financial_report_operating_unit/__manifest__.py
  account_financial_report_operating_unit/static/description/index.html
Labels: bot is merging ⏳

#746 [15.0][IMP] account_financial_report_operating_unit: add OU in abstract model
  account_financial_report_operating_unit/wizards/__init__.py
  account_financial_report_operating_unit/wizards/abstract_wizard.py
  account_financial_report_operating_unit/wizards/aged_partner_balance_wizard.py
  account_financial_report_operating_unit/wizards/general_ledger_wizard.py
  account_financial_report_operating_unit/wizards/journal_ledger_wizard.py
  account_financial_report_operating_unit/wizards/journal_ledger_wizard_view.xml
  account_financial_report_operating_unit/wizards/open_items_wizard.py
  account_financial_report_operating_unit/wizards/trial_balance_wizard.py
Labels: approved, bot is merging ⏳
