Repository OCA/operating-unit, pull requests merged in 2025-06, with the labels that each got.

#772 [18.0][MIG] account_operating_unit: Migration to 18.0
  account_operating_unit/README.rst
  account_operating_unit/__init__.py
  account_operating_unit/__manifest__.py
  account_operating_unit/i18n/account_operating_unit.pot
  account_operating_unit/i18n/es_MX.po
  account_operating_unit/i18n/it.po
  account_operating_unit/models/__init__.py
  account_operating_unit/models/account_bank_statement.py
  account_operating_unit/models/account_journal.py
  account_operating_unit/models/account_move.py
  account_operating_unit/models/account_partial_reconcile.py
  account_operating_unit/models/account_payment.py
  account_operating_unit/models/res_company.py
  account_operating_unit/pyproject.toml
  account_operating_unit/readme/CONFIGURE.md
  account_operating_unit/readme/CONTRIBUTORS.md
  account_operating_unit/readme/DESCRIPTION.md
  account_operating_unit/readme/ROADMAP.md
  account_operating_unit/readme/USAGE.md
  account_operating_unit/report/__init__.py
  account_operating_unit/report/account_invoice_report.py
  account_operating_unit/security/account_security.xml
  account_operating_unit/static/description/icon.png
  account_operating_unit/static/description/index.html
  account_operating_unit/tests/__init__.py
  account_operating_unit/tests/test_account_operating_unit.py
  account_operating_unit/tests/test_account_reconcile.py
  account_operating_unit/tests/test_cross_ou_journal_entry.py
  account_operating_unit/tests/test_invoice_operating_unit.py
  account_operating_unit/tests/test_operating_unit_security.py
  account_operating_unit/tests/test_payment_operating_unit.py
  account_operating_unit/views/account_invoice_report_view.xml
  account_operating_unit/views/account_journal_view.xml
  account_operating_unit/views/account_move_view.xml
  account_operating_unit/views/account_payment_view.xml
  account_operating_unit/views/company_view.xml
Labels: approved, bot is merging ⏳

#766 [14.0][FIX] operating_unit: get default OU from correct field
  operating_unit/models/res_users.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/res_users_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#774 [16.0][FIX] operating_unit: get default OU from correct field
  operating_unit/models/res_users.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/res_users_view.xml
Labels: bot is merging ⏳

#773 [15.0][FIX] operating_unit: get default OU from correct field
  operating_unit/models/res_users.py
  operating_unit/tests/test_operating_unit.py
  operating_unit/view/res_users_view.xml
Labels: bot is merging ⏳

#752 [18.0][MIG] operating_unit_access_all: Migration to 18.0
  operating_unit_access_all/README.rst
  operating_unit_access_all/__init__.py
  operating_unit_access_all/__manifest__.py
  operating_unit_access_all/i18n/it.po
  operating_unit_access_all/i18n/operating_unit_access_all.pot
  operating_unit_access_all/pyproject.toml
  operating_unit_access_all/readme/CONFIGURE.md
  operating_unit_access_all/readme/CONTRIBUTORS.md
  operating_unit_access_all/readme/DESCRIPTION.md
  operating_unit_access_all/security/operating_unit_security.xml
  operating_unit_access_all/static/description/icon.png
  operating_unit_access_all/static/description/index.html
Labels: approved, bot is merging ⏳

#778 [17.0][FIX] account_operating_unit: account.move form view
  account_operating_unit/views/account_move_view.xml
Labels: approved, ready to merge, merged 🎉
