Repository OCA/operating-unit, pull requests merged in 2025-07, with the labels that each got.

#753 [18.0][MIG] purchase_operating_unit: Migration to 18.0
  purchase_operating_unit/README.rst
  purchase_operating_unit/__init__.py
  purchase_operating_unit/__manifest__.py
  purchase_operating_unit/demo/purchase_order_demo.xml
  purchase_operating_unit/i18n/it.po
  purchase_operating_unit/i18n/purchase_operating_unit.pot
  purchase_operating_unit/models/__init__.py
  purchase_operating_unit/models/account_move.py
  purchase_operating_unit/models/purchase_order.py
  purchase_operating_unit/pyproject.toml
  purchase_operating_unit/readme/CONTRIBUTORS.md
  purchase_operating_unit/readme/DESCRIPTION.md
  purchase_operating_unit/readme/USAGE.md
  purchase_operating_unit/report/__init__.py
  purchase_operating_unit/report/purchase_report.py
  purchase_operating_unit/report/purchase_report_view.xml
  purchase_operating_unit/security/purchase_security.xml
  purchase_operating_unit/static/description/icon.png
  purchase_operating_unit/static/description/index.html
  purchase_operating_unit/tests/__init__.py
  purchase_operating_unit/tests/test_po_security.py
  purchase_operating_unit/tests/test_purchase_operating_unit.py
  purchase_operating_unit/views/account_move_view.xml
  purchase_operating_unit/views/purchase_order_line_view.xml
  purchase_operating_unit/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#600 [16.0] [MIG] sale_operating_unit
  sale_operating_unit/README.rst
  sale_operating_unit/__init__.py
  sale_operating_unit/__manifest__.py
  sale_operating_unit/i18n/sale_operating_unit.pot
  sale_operating_unit/models/__init__.py
  sale_operating_unit/models/crm_team.py
  sale_operating_unit/models/sale_order.py
  sale_operating_unit/readme/CONTRIBUTORS.rst
  sale_operating_unit/readme/DESCRIPTION.rst
  sale_operating_unit/readme/ROADMAP.rst
  sale_operating_unit/readme/USAGE.rst
  sale_operating_unit/report/__init__.py
  sale_operating_unit/report/sale_report.py
  sale_operating_unit/security/sale_security.xml
  sale_operating_unit/static/description/icon.png
  sale_operating_unit/static/description/index.html
  sale_operating_unit/tests/__init__.py
  sale_operating_unit/tests/test_sale_operating_unit.py
  sale_operating_unit/views/sale_report_view.xml
  sale_operating_unit/views/sale_view.xml
  sale_operating_unit/wizard/__init__.py
  sale_operating_unit/wizard/sale_make_invoice_advance.py
  setup/sale_operating_unit/odoo/addons/sale_operating_unit
  setup/sale_operating_unit/setup.py
Labels: needs review, migration, bot is merging ⏳, no stale

#782 [15.0][IMP] crm_operating_unit: remove unused deafult OU in leads
  crm_operating_unit/models/crm_lead.py
  crm_operating_unit/tests/test_crm_operating_unit.py
Labels: approved, ready to merge, bot is merging ⏳

#789 [15.0][FIX] operating_unit: allow access to user without all companies active
  operating_unit/models/res_users.py
Labels: bot is merging ⏳
